### ISSUE TITLE
TypeError: unbound method reject() must be called with Promise instance as first argument

### ISSUE THREAD

**Issue by cmeadows** [syrusakbary/promise#2]
I have tried the following:

`except Exception, e:`
`     return Promise.reject(e)`

`return Promise.reject(Exception(e))`

Both return the following error:

`TypeError: unbound method reject() must be called with Promise instance as first argument (got Exception instance instead)`

**Comment by syrusakbary** [comment]
You should use `Promise.rejected` instead 😉 
Closing issue
