### ISSUE TITLE
2.0.1 tag?

### ISSUE THREAD

**Issue by boneill42** [syrusakbary/promise#28]
I see that 2.0.1 is available on PyPi, but I don't see a corresponding tag.
https://pypi.python.org/pypi/promise/2.0.1

Is there a way to determine what code went out in that release?

**Comment by syrusakbary** [comment]
Sorry, I missed creating a tag. 
I just created one with the changelog: https://github.com/syrusakbary/promise/releases/tag/v2.0.1

Thanks for reporting it!
