### ISSUE TITLE
Question: compatibility with asyncio's event loop? 

### ISSUE THREAD

**Issue by bevensteven** [syrusakbary/promise#6]
Hi,

Great module you got going on! I am attempting to make Python function identically to NodeJS as part of a personal project. Currently, I am using your Promises in a fashion that follows A+ but still have some trouble understanding how this module would interact with an `asyncio` event loop.

Does the event loop recognize when a `Promise` is `fulfilled` - similarly to how an `asyncio.Future` is given a result (via `set_result`) and marked as done? 

If you have time, a toy example implementation of using your Promises with the `asyncio` event loop (mimicking Node's event loop) would help a lot.

Thanks!

**Comment by syrusakbary** [comment]
Yep, you can safely use `Promise` in `asyncio` as if you were using `couroutine`s or `Future`s :)

It's also tested :)
https://github.com/syrusakbary/promise/blob/master/tests/test_awaitable_35.py
