### ISSUE TITLE
How thread safe are promises?

### ISSUE THREAD

**Issue by dongryphon** [syrusakbary/promise#68]
After reading through the source for some time I do not see any use of locks (like the imported and ignored `from threading import RLock`) to protect one thread adding a callback to a promise instance from another thread that is resolving/rejecting that promise...

So is such use of a promise invalid or does it work because of the GIL? ... or something else?

Thanks for the awesome code!

**Comment by dongryphon** [comment]
Would really appreciate even a couple words of wisdom on this...

**Comment by dongryphon** [comment]
Is this the proper place to ask questions?

**Comment by chroth** [comment]
@PepperTeasdale It sounds like your issue is related to https://github.com/syrusakbary/promise/issues/57

**Comment by syrusakbary** [comment]
The PR #81 has been merged. Promises should be now thread-safe in Promise 2.3.0
