### ISSUE TITLE
Python-futures is a python-2 only package

### ISSUE THREAD

**Issue by Millak** [syrusakbary/promise#7]
When I attempt to run the test suite using python-3, it complains about futures missing.

**Comment by syrusakbary** [comment]
Hi @Millak, which version of Python are you testing with?
In my developing environment I test with Python 2.7 and 3.5, but Travis also checks compatibility with 3.3, 3.4 and 3.5 https://travis-ci.org/syrusakbary/promise

**Comment by syrusakbary** [comment]
Closing the issue. Please reopen if you are unable to run promise tests on those environments. (or open a PR for supporting older Python versions (3.2, 3.3))
